### PR TITLE
Rake integration

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR adds Opbeat reporting for Rake tasks.

Questions:
- When should this add-on be loaded? Always? On demand by the user? If Rake is loaded?

CC: @jensnockert

### CODE REVIEW

**Comment by mikker** [comment]
This is great! Thank you.

I think we ought to come up with some kind of setting to enable/disable integrations. See fx #21 .

My initial thought is to add `opbeat.config.enabled_integrations = [:sidekiq, :rake, :active_record]` or something like that. Then we can just add manual checks in every integration with a simple `opbeat.config.enabled.include?(:sidekiq)`.

Sounds reasonable?

**Comment by jensnockert** [comment]
I think that idea sounds good @mikker.

After considering this over lunch, I think me and @olleolleolle should add some tests to check the extra data too.

**Comment by mikker** [comment]
Good! Would like to take a stab at implementing the integration config?

**Comment by olleolleolle** [comment]
Hello, here's a status update.

The stab that I saved on my computer and then did not finish was: "Keep all of the potentially-poisonous patches to Other Software in files which are not automatically included, and load and apply them only after the configuration has told it to."

That means a bit of reorganization of the file tree, and some decision-making on what goes into the default list of enabled things.

We also tried our hand at grouping things that the user would be less interested in keeping separate. Not sure about the state of those things.

I am not currently going to finish this on my own. Is there a way to scale it back, make the change smaller, again?

**Comment by mikker** [comment]
Sounds reasonable, @olleolleolle. Do you mean if there's a way in git to cut the drastic changes to this branch? I'd make this look like I wanted it to then `fixup` every commit into one using `git rebase -i master` (or `git rebase -i origin/master` if you're already on your own `master`).

**Comment by olleolleolle** [comment]
@mikker Sorry, no, not git, just saying "I'd like to withdraw the change's scope to just be an ugly patch of Rake" that you get whatever you do.

**Comment by olleolleolle** [comment]
I’ll not finish this.

**Comment by mikker** [comment]
@olleolleolle No sweat! Good news though: All this will be in our new APM solution at @elastic! I hope you'll give it a go when I make the ✨ brand new ✨ lib public. Can't tell you when -- but you probably won't have to wait _too long_. See more at https://www.elastic.co/solutions/apm

**Pull request closed without merging**
